### ISSUE TITLE
IHP-130 technology

### ISSUE THREAD

**Issue by mrwolfie123** [aesc-silicon/i2c-gpio-expander#1]
We are currently engaged in a research project that requires detailed information and technical data related to the IHP-130nm layout technology. Specifically, we are seeking comprehensive documentation and layout details to support our design and implementation processes.

Could you kindly provide us with the necessary resources or guide us on how to obtain the relevant information? Any assistance or direction you can offer would be immensely valuable to our project.

**Comment by dnltz** [comment]
Hey @mrwolfie123, the entire PDK as well as documentation is hosted here on GitHub: https://github.com/IHP-GmbH/IHP-Open-PDK. In case you need more information, I would recommend you to join the open source silicon (https://open-source-silicon.dev/) Slack workspace. There is an `ihp-sg13g2` channel to chat with all person who are involved with that PDK.
